[project]
name = "pyinventory_ynh"
dynamic = ["version"]
description = "Web based management to catalog things including state and location etc."
license = {text = "GPL-3.0-or-later"}
readme = "README.md"
authors = [
    {name = 'Jens Diemer', email = 'pyinventory_ynh@jensdiemer.de'}
]

# Match: https://github.com/jedie/PyInventory/blob/main/pyproject.toml
requires-python = ">=3.14"  # (YunoHost installation will install Python via uv)
dependencies = [
    "pyinventory>=0.25.0",  # https://github.com/jedie/PyInventory
    "django_yunohost_integration>=0.11.0",  # https://github.com/YunoHost-Apps/django_yunohost_integration
    "Django",  # https://www.djangoproject.com/
    'gunicorn',
    'psycopg[binary]', # https://github.com/psycopg/psycopg
    'django-redis',
    'django-axes', # https://github.com/jazzband/django-axes
]
[dependency-groups]
dev = [
    "django-debug-toolbar",  # http://django-debug-toolbar.readthedocs.io/en/stable/changes.html
    "manage_django_project",  # https://github.com/jedie/manage_django_project
    "manageprojects",  # https://github.com/jedie/manageprojects
    "bx_django_utils",  # https://github.com/boxine/bx_django_utils
    "beautifulsoup4",  # https://pypi.org/project/beautifulsoup4/
    "uv",  # https://github.com/astral-sh/uv
    "tblib",   # https://github.com/ionelmc/python-tblib
    "nox",  # https://github.com/wntrblm/nox
    "coverage",  # https://github.com/nedbat/coveragepy
    "ruff", # https://github.com/astral-sh/ruff
    "codespell",  # https://github.com/codespell-project/codespell
    "EditorConfig",  # https://github.com/editorconfig/editorconfig-core-py
    "pip-audit",  # https://github.com/pypa/pip-audit
    "mypy",  # https://github.com/python/mypy
    "twine",  # https://github.com/pypa/twine
    "typeguard",  # https://github.com/agronholm/typeguard/
]


[tool.uv]
# Don't install bleed-edge versions of dependencies, to avoid undetected issues and supply chain attacks.
exclude-newer = "1 week"

[tool.uv.exclude-newer-package]
# Exclude own packages from the "exclude-newer" rule and
# add external packages temporarily to fix known issues or current CVEs
cryptography = "2026-08-08T12:00:00Z"
# Own projects:
pyinventory = "2026-08-08T13:00:00Z"
django_yunohost_integration = "2026-08-08T15:00:00Z"
django-tools = "2026-08-08T12:00:00Z"
manage_django_project = "2026-08-08T12:22:00Z"
cmd2 = "2026-08-08T12:00:00Z"


[tool.cli_base.pip_audit]
strict=true
require_hashes=true
ignore-vuln=[
    # e.g.: "CVE-2026-1234",
]


[project.urls]
Documentation = "https://github.com/YunoHost-Apps/pyinventory_ynh"
Source = "https://github.com/YunoHost-Apps/pyinventory_ynh"


[ynh-integration]
local_settings_source= "local_settings_source.py"


[build-system]
requires = ["setuptools>=61.0", "setuptools_scm>=7.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["pyinventory_ynh*"]

[tool.setuptools.dynamic]
version = {attr = "pyinventory_ynh.__version__"}


[tool.ruff]
# https://docs.astral.sh/ruff/configuration/
line-length = 120
exclude = [
  ".*/","*/htmlcov/*","*/migrations/*","*/local_test/*"
]

[tool.ruff.lint]
preview = true  # Needed for some of the rules
extend-select = [
    "E", # pycodestyle: https://docs.astral.sh/ruff/rules/#error-e
    "I", # isort: https://docs.astral.sh/ruff/rules/#isort-i
]
ignore = [
    "E402", # https://docs.astral.sh/ruff/rules/module-import-not-at-top-of-file/
    "E731", # https://docs.astral.sh/ruff/rules/lambda-assignment/
]

[tool.ruff.lint.isort]
# https://docs.astral.sh/ruff/settings/#lintisort
lines-after-imports = 2

[tool.ruff.format]
quote-style = "single"


[tool.coverage.run]
# https://coverage.readthedocs.io/en/latest/config.html#run
branch = true
parallel = true
concurrency = ["multiprocessing"]
source = ['.']
command_line = './dev-cli.py test'
disable_warnings = ["couldnt-parse"]
data_file = ".coverage_data/.coverage"

[tool.coverage.report]
omit = ['.*', '*/tests/*']
skip_empty = true
fail_under = 10
show_missing = true
exclude_lines = [
    'if self.debug:',
    'pragma: no cover',
    'raise NotImplementedError',
    'if __name__ == .__main__.:',
]


[tool.mypy]
warn_unused_configs = true
ignore_missing_imports = true
allow_redefinition = true  # https://github.com/python/mypy/issues/7165
show_error_codes = true
plugins = []
exclude = ['.venv', 'tests']


[manageprojects] # https://github.com/jedie/manageprojects
initial_revision = "b204761"
initial_date = 2022-12-21T20:25:20+01:00
cookiecutter_template = "https://github.com/jedie/cookiecutter_templates/"
cookiecutter_directory = "yunohost_django_package"
applied_migrations = [
    "2cdc1d8", # 2024-08-25T19:00:41+02:00
    "6fa011a", # 2024-09-07T11:11:40+02:00
    "b3d9208", # 2024-12-23T17:04:43+01:00
    "d1df540", # 2025-01-11T08:58:27+01:00
    "c059f97", # 2025-03-21T19:19:56+01:00
    "279f2d0", # 2025-09-15T16:30:52+02:00
    "ae399b9", # 2025-09-21T09:34:36+02:00
    "38082ef", # 2025-10-16T10:28:32+02:00
    "c425447", # 2025-11-02T17:01:35+01:00
    "ee2e451", # 2026-08-08T13:51:46+02:00
]

[manageprojects.cookiecutter_context.cookiecutter]
project_name = "PyInventory"
project_id = "pyinventory"
full_name = "Jens Diemer"
github_username = "jedie"
author_email = "pyinventory_ynh@jensdiemer.de"
upstream_pkg_name = "inventory_project"
upstream_pkg_app_name = "inventory"
upstream_pkg_project_name = "pyinventory"
upstream_url = "https://github.com/jedie/PyInventory"
ynh_app_pkg_name = "pyinventory_ynh"
ynh_app_url = "https://github.com/YunoHost-Apps/pyinventory_ynh"
bug_tracker_url = "https://github.com/jedie/PyInventory/issues"
upstream_version = "0.24.0"
ynh_suffix_version = "ynh2"
package_description = "Web based management to catalog things including state and location etc."
license = "GPL-3.0-or-later"
_template = "https://github.com/jedie/cookiecutter_templates/"
