#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh

# https://doc.yunohost.org/en/dev/packaging/scripts/helpers_v2.1
source /usr/share/yunohost/helpers

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

# /var/www/$app/
ynh_backup "$install_dir"

# /home/yunohost.app/$app/
ynh_backup "$data_dir"

#=================================================
# BACKUP VARIOUS FILES
#=================================================

ynh_backup "$(dirname "$log_file")"

#=================================================
# BACKUP THE PostgreSQL DATABASE
#=================================================

ynh_psql_dump_db > db.sql

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
