#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh

# https://doc.yunohost.org/en/dev/packaging/scripts/helpers_v2.1
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping systemd service '$app'..."

ynh_systemctl --service=$app --action="stop" --log_path="$log_file"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating nginx web server configuration..."

ynh_config_change_url_nginx

#=================================================
# UPDATE DJANGO SETTINGS
#=================================================
ynh_script_progression "Update $app settings file..."

path=$new_path
domain=$new_domain

ynh_config_add --template="settings.py" --destination="$data_dir/settings.py"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting systemd service '$app'..."

ynh_systemctl --service=$app --action="start" --log_path="$log_file"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
