#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

# Remove a service from the admin panel, added by `yunohost service add`
if yunohost service status $app >/dev/null 2>&1
then
	ynh_script_progression "Removing $app service integration..."
	yunohost service remove $app
fi

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the app-specific systemd service
ynh_config_remove_systemd

# Remove the app-specific Redis
ynh_redis_remove_db

# Remove the app-specific nginx config
ynh_config_remove_nginx

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_script_progression "Removing app main directory..."

# /var/www/$app/
ynh_safe_rm "$install_dir"

# /home/yunohost.app/$app/
ynh_safe_rm "$data_dir"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Removal of $app completed"
