#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh

# https://doc.yunohost.org/en/dev/packaging/scripts/helpers_v2.1
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring $install_dir..."
# /var/www/$app/
ynh_restore "$install_dir"

ynh_script_progression "Restoring $data_dir..."
# /home/yunohost.app/$app/
ynh_restore "$data_dir"


# See conf/gunicorn.conf.py
if [ -f "$data_dir/gunicorn.pid" ]; then ynh_safe_rm "$data_dir/gunicorn.pid"; fi


ynh_script_progression "Set $app file permissions..."
myynh_fix_file_permissions

ynh_script_progression "Setup Python virtualenv for $app ..."
# # Maybe the backup contains a other Python version
myynh_setup_python_venv

#=================================================
# RESTORE THE PostgreSQL DATABASE
#=================================================
ynh_script_progression "Restoring the PostgreSQL database..."

ynh_psql_db_shell < ./db.sql

#=================================================
# SETUP LOG FILE
#=================================================
ynh_script_progression "Setup logging..."

myynh_setup_log_file

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate "$log_file"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx
ynh_config_add_systemd
yunohost service add --description $app $app

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================
ynh_script_progression "Set $app file permissions..."
myynh_fix_file_permissions

#=================================================
# Start the app server via systemd
#=================================================
ynh_script_progression "Starting systemd service '$app'..."

ynh_systemctl --service=$app --action="start" --log_path=systemd

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression "Reloading nginx web server..."

ynh_systemctl --service="nginx" --action="reload"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Restoration completed for $app"
