#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh

# https://doc.yunohost.org/en/dev/packaging/scripts/helpers_v2.1
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the $app files..."

ynh_restore_everything

# See conf/gunicorn.conf.py
if [ -f "$data_dir/gunicorn.pid" ]; then ynh_safe_rm "$data_dir/gunicorn.pid"; fi

ynh_script_progression "Set $app file permissions..."
myynh_fix_file_permissions

ynh_script_progression "Setup Python virtualenv for $app ..."
# # Maybe the backup contains a other Python version
myynh_setup_python_venv

#=================================================
# RESTORE THE PostgreSQL DATABASE
#=================================================
ynh_script_progression "Restoring the PostgreSQL database..."

ynh_psql_db_shell < ./db.sql

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

systemctl enable $app.service --quiet

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate "$log_file"

ynh_script_progression "Integrating service in YunoHost..."

yunohost service add --description $app $app

#=================================================
# START APP
#=================================================
ynh_script_progression "Starting systemd service '$app'..."

ynh_systemctl --service=$app --action="start" --log_path="$log_file"

ynh_script_progression "Reloading nginx web server..."

ynh_systemctl --service="nginx" --action="reload"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Restoration completed for $app"
