name: YunoHost apps package linter

on:
  # Allow to manually trigger the workflow
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 8 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml

      - name: 'Clone YunoHost apps package linter'
        run: |
          git clone --depth=1 https://github.com/YunoHost/package_linter ~/package_linter

      - name: 'Install requirements'
        run: pip3 install toml

      - name: 'Run linter'
        run: |
          ~/package_linter/package_linter.py .
